/* =========================================================
   RennXCare — Structured Agency Data
   50 placeholder agencies across California.
   Replace or extend with real agency records.
   ========================================================= */

/* ------------------------------------------------------------------
   AGENCY RECORDS
   Fields: id, name, slug, city, citySlug, county, state, zip,
           phone, address, lat, lng, rating, reviewCount,
           services, description, longDescription, founded,
           licenseNumber, featured, rxCarePartner, hours
   ------------------------------------------------------------------ */
const RENNXCARE_AGENCIES = [

  /* ---- Los Angeles (10) ---- */
  {
    id: 1,
    name: "Sunrise Senior Care",
    slug: "sunrise-senior-care",
    city: "Los Angeles",
    citySlug: "los-angeles",
    county: "Los Angeles County",
    state: "CA",
    zip: "90025",
    phone: "(310) 555-0101",
    address: "11600 Wilshire Blvd, Suite 200, Los Angeles, CA 90025",
    lat: 34.0522,
    lng: -118.4437,
    rating: 4.9,
    reviewCount: 63,
    services: ["Personal Care", "Dementia Care", "24-Hour Care", "Companionship"],
    description: "Sunrise Senior Care has served Los Angeles families since 2015 with fully background-checked, trained caregivers.",
    longDescription: "Sunrise Senior Care is a family-owned in-home care agency serving greater Los Angeles since 2015. Our caregivers are thoroughly background-checked, CPR-certified, and trained in dementia and Alzheimer's care. We specialize in personal care, 24-hour live-in care, and companion services for seniors who wish to age safely at home.",
    founded: 2015,
    licenseNumber: "CA-HCA-2015-001",
    featured: true,
    rxCarePartner: true,
    hours: "Mon–Sun: 7am–8pm, 24-hr on-call",
  },
  {
    id: 2,
    name: "Pacific Home Care Partners",
    slug: "pacific-home-care-partners",
    city: "Los Angeles",
    citySlug: "los-angeles",
    county: "Los Angeles County",
    state: "CA",
    zip: "90066",
    phone: "(310) 555-0202",
    address: "4560 Sepulveda Blvd, Los Angeles, CA 90066",
    lat: 33.9989,
    lng: -118.4246,
    rating: 4.7,
    reviewCount: 41,
    services: ["Personal Care", "Respite Care", "Hospice Support"],
    description: "Pacific Home Care Partners provides compassionate respite and hospice support care across West Los Angeles.",
    longDescription: "Pacific Home Care Partners focuses on supporting family caregivers through respite care and providing dignified hospice support services. Serving West LA and Mar Vista neighborhoods, our team coordinates with hospice nurses and social workers to ensure a seamless care experience.",
    founded: 2017,
    licenseNumber: "CA-HCA-2017-008",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Fri: 8am–6pm, On-call weekends",
  },
  {
    id: 3,
    name: "Valley Senior Solutions",
    slug: "valley-senior-solutions",
    city: "Los Angeles",
    citySlug: "los-angeles",
    county: "Los Angeles County",
    state: "CA",
    zip: "91401",
    phone: "(818) 555-0303",
    address: "7240 Van Nuys Blvd, Van Nuys, CA 91401",
    lat: 34.1908,
    lng: -118.4498,
    rating: 4.6,
    reviewCount: 38,
    services: ["Personal Care", "Dementia Care", "Meal Preparation", "Transportation"],
    description: "Valley Senior Solutions specializes in dementia care and daily living support across the San Fernando Valley.",
    longDescription: "Valley Senior Solutions brings expert dementia and memory care to seniors in Van Nuys, Sherman Oaks, and the greater San Fernando Valley. Our specialized caregivers use proven memory engagement techniques and provide safe, structured daily routines to promote dignity and independence.",
    founded: 2016,
    licenseNumber: "CA-HCA-2016-014",
    featured: false,
    rxCarePartner: true,
    hours: "Mon–Sun: 7am–9pm",
  },
  {
    id: 4,
    name: "Westside Home Health",
    slug: "westside-home-health",
    city: "Los Angeles",
    citySlug: "los-angeles",
    county: "Los Angeles County",
    state: "CA",
    zip: "90403",
    phone: "(310) 555-0404",
    address: "2800 Santa Monica Blvd, Santa Monica, CA 90403",
    lat: 34.0195,
    lng: -118.4912,
    rating: 4.8,
    reviewCount: 55,
    services: ["Personal Care", "24-Hour Care", "Medication Reminders", "Companionship"],
    description: "Westside Home Health delivers premium in-home care for seniors in Santa Monica, Brentwood, and Pacific Palisades.",
    longDescription: "Westside Home Health offers premium non-medical in-home care along the coast and in Westside neighborhoods. We specialize in 24-hour care, overnight shifts, and building strong caregiver-client relationships. All caregivers pass a rigorous 9-step hiring and training process.",
    founded: 2014,
    licenseNumber: "CA-HCA-2014-005",
    featured: true,
    rxCarePartner: false,
    hours: "24/7 availability",
  },
  {
    id: 5,
    name: "Southland Elder Care",
    slug: "southland-elder-care",
    city: "Los Angeles",
    citySlug: "los-angeles",
    county: "Los Angeles County",
    state: "CA",
    zip: "90016",
    phone: "(323) 555-0505",
    address: "3550 W Adams Blvd, Los Angeles, CA 90016",
    lat: 34.0254,
    lng: -118.3498,
    rating: 4.5,
    reviewCount: 29,
    services: ["Personal Care", "Respite Care", "Light Housekeeping"],
    description: "Southland Elder Care serves Mid-City and South Los Angeles families with affordable, dignified in-home support.",
    longDescription: "Southland Elder Care is committed to making quality home care accessible for families in Mid-City and South Los Angeles. We offer flexible scheduling, affordable hourly rates, and bilingual (English/Spanish) caregivers who understand the cultural needs of our diverse client community.",
    founded: 2019,
    licenseNumber: "CA-HCA-2019-022",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sat: 8am–7pm",
  },
  {
    id: 6,
    name: "Angeles In-Home Care",
    slug: "angeles-in-home-care",
    city: "Los Angeles",
    citySlug: "los-angeles",
    county: "Los Angeles County",
    state: "CA",
    zip: "90027",
    phone: "(323) 555-0606",
    address: "4233 Sunset Blvd, Los Angeles, CA 90027",
    lat: 34.0880,
    lng: -118.2916,
    rating: 4.7,
    reviewCount: 44,
    services: ["Dementia Care", "Personal Care", "Companionship", "24-Hour Care"],
    description: "Angeles In-Home Care offers expert dementia and Alzheimer's care across Silver Lake, Los Feliz, and Hollywood.",
    longDescription: "Angeles In-Home Care is recognized for exceptional dementia and Alzheimer's support across the East Hollywood and Silver Lake corridor. Our caregivers hold specialized memory care training certificates and partner with families to create individualized care plans that evolve with each client's needs.",
    founded: 2013,
    licenseNumber: "CA-HCA-2013-003",
    featured: false,
    rxCarePartner: true,
    hours: "Mon–Sun: 6am–10pm",
  },
  {
    id: 7,
    name: "First Choice Home Care",
    slug: "first-choice-home-care",
    city: "Los Angeles",
    citySlug: "los-angeles",
    county: "Los Angeles County",
    state: "CA",
    zip: "90041",
    phone: "(323) 555-0707",
    address: "5116 Eagle Rock Blvd, Los Angeles, CA 90041",
    lat: 34.1394,
    lng: -118.2100,
    rating: 4.6,
    reviewCount: 31,
    services: ["Personal Care", "Meal Preparation", "Transportation", "Errands"],
    description: "First Choice Home Care provides daily living support and errands assistance in Eagle Rock and Northeast LA.",
    longDescription: "First Choice Home Care helps seniors maintain independence in Northeast Los Angeles neighborhoods including Eagle Rock, Highland Park, and Atwater Village. Our holistic daily living support includes meal prep, transportation to medical appointments, grocery runs, and light housekeeping—so seniors can thrive at home.",
    founded: 2018,
    licenseNumber: "CA-HCA-2018-019",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Fri: 7am–7pm",
  },
  {
    id: 8,
    name: "Golden State Senior Care",
    slug: "golden-state-senior-care",
    city: "Los Angeles",
    citySlug: "los-angeles",
    county: "Los Angeles County",
    state: "CA",
    zip: "90232",
    phone: "(310) 555-0808",
    address: "9001 Venice Blvd, Culver City, CA 90232",
    lat: 34.0078,
    lng: -118.3991,
    rating: 4.8,
    reviewCount: 52,
    services: ["Personal Care", "24-Hour Care", "Dementia Care", "Hospice Support"],
    description: "Golden State Senior Care is a full-service in-home care agency serving Culver City and the surrounding area.",
    longDescription: "Golden State Senior Care brings together a team of experienced caregivers and care coordinators to deliver high-quality non-medical in-home care in Culver City, West Adams, and surrounding communities. We offer comprehensive care plans including 24-hour, overnight, and live-in services with nurse oversight available.",
    founded: 2011,
    licenseNumber: "CA-HCA-2011-002",
    featured: true,
    rxCarePartner: true,
    hours: "24/7 availability",
  },
  {
    id: 9,
    name: "Metro Home Health Services",
    slug: "metro-home-health-services",
    city: "Los Angeles",
    citySlug: "los-angeles",
    county: "Los Angeles County",
    state: "CA",
    zip: "90020",
    phone: "(213) 555-0909",
    address: "3780 Wilshire Blvd, Los Angeles, CA 90020",
    lat: 34.0625,
    lng: -118.3076,
    rating: 4.5,
    reviewCount: 28,
    services: ["Personal Care", "Medication Reminders", "Companionship", "Light Housekeeping"],
    description: "Metro Home Health Services delivers dependable personal care and companionship in Koreatown and Central LA.",
    longDescription: "Metro Home Health Services is a multilingual agency serving Koreatown, Westlake, and Central Los Angeles. We have Korean-, Spanish-, and English-speaking caregivers available to match the cultural preferences of our diverse clientele. Care is available from 4-hour minimum blocks up to full 24-hour coverage.",
    founded: 2020,
    licenseNumber: "CA-HCA-2020-031",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sun: 8am–8pm",
  },
  {
    id: 10,
    name: "LA Companion Care Network",
    slug: "la-companion-care-network",
    city: "Los Angeles",
    citySlug: "los-angeles",
    county: "Los Angeles County",
    state: "CA",
    zip: "90230",
    phone: "(310) 555-1010",
    address: "6100 Centinela Ave, Culver City, CA 90230",
    lat: 33.9918,
    lng: -118.4038,
    rating: 4.6,
    reviewCount: 35,
    services: ["Companionship", "Transportation", "Errands", "Meal Preparation"],
    description: "LA Companion Care Network focuses on social engagement, transportation, and lifestyle support for active seniors.",
    longDescription: "LA Companion Care Network serves seniors who are largely independent but benefit from regular social engagement, transportation to activities, and lifestyle support. Our friendly, energetic companions help clients stay connected to community, hobbies, and family—combating isolation and supporting mental wellness.",
    founded: 2021,
    licenseNumber: "CA-HCA-2021-038",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Fri: 9am–6pm",
  },

  /* ---- San Diego (7) ---- */
  {
    id: 11,
    name: "Coastal Senior Care",
    slug: "coastal-senior-care",
    city: "San Diego",
    citySlug: "san-diego",
    county: "San Diego County",
    state: "CA",
    zip: "92101",
    phone: "(619) 555-1101",
    address: "1450 Front St, San Diego, CA 92101",
    lat: 32.7157,
    lng: -117.1611,
    rating: 4.9,
    reviewCount: 71,
    services: ["Personal Care", "Dementia Care", "24-Hour Care", "Companionship"],
    description: "Coastal Senior Care is San Diego's highest-rated in-home agency, serving downtown and coastal neighborhoods.",
    longDescription: "Coastal Senior Care has earned San Diego's trust with exceptional personal care, dementia support, and round-the-clock services. Families across downtown San Diego, Mission Hills, and North Park choose us for our responsive care coordinators and carefully matched caregiver placements.",
    founded: 2012,
    licenseNumber: "CA-HCA-2012-006",
    featured: true,
    rxCarePartner: true,
    hours: "24/7 availability",
  },
  {
    id: 12,
    name: "San Diego Home Health Network",
    slug: "san-diego-home-health-network",
    city: "San Diego",
    citySlug: "san-diego",
    county: "San Diego County",
    state: "CA",
    zip: "92108",
    phone: "(619) 555-1202",
    address: "5645 Friars Rd, San Diego, CA 92108",
    lat: 32.7673,
    lng: -117.1508,
    rating: 4.7,
    reviewCount: 49,
    services: ["Personal Care", "Respite Care", "Hospice Support"],
    description: "San Diego Home Health Network offers specialized respite and hospice support with a compassionate care team.",
    longDescription: "San Diego Home Health Network partners with local hospice organizations, hospitals, and skilled nursing facilities to provide seamless transitions and family-centered care. Our respite care services give primary caregivers the breaks they need while seniors receive consistent, professional support.",
    founded: 2016,
    licenseNumber: "CA-HCA-2016-015",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sun: 7am–9pm",
  },
  {
    id: 13,
    name: "Bayview Elder Care",
    slug: "bayview-elder-care",
    city: "San Diego",
    citySlug: "san-diego",
    county: "San Diego County",
    state: "CA",
    zip: "92118",
    phone: "(619) 555-1303",
    address: "1010 Orange Ave, Coronado, CA 92118",
    lat: 32.6859,
    lng: -117.1831,
    rating: 4.8,
    reviewCount: 43,
    services: ["Personal Care", "24-Hour Care", "Medication Reminders"],
    description: "Bayview Elder Care serves Coronado and South Bay with attentive, personalized in-home care services.",
    longDescription: "Bayview Elder Care brings white-glove in-home care to Coronado Island and South Bay communities. We are known for our meticulous caregiver matching process and high caregiver retention, ensuring seniors see familiar, trusted faces in their homes every visit.",
    founded: 2018,
    licenseNumber: "CA-HCA-2018-020",
    featured: false,
    rxCarePartner: true,
    hours: "Mon–Sun: 7am–9pm",
  },
  {
    id: 14,
    name: "Pacific Crest Home Care",
    slug: "pacific-crest-home-care",
    city: "San Diego",
    citySlug: "san-diego",
    county: "San Diego County",
    state: "CA",
    zip: "92122",
    phone: "(858) 555-1404",
    address: "4445 Eastgate Mall, San Diego, CA 92122",
    lat: 32.8731,
    lng: -117.2125,
    rating: 4.6,
    reviewCount: 37,
    services: ["Dementia Care", "Companionship", "Transportation", "Light Housekeeping"],
    description: "Pacific Crest Home Care specializes in memory care and social engagement for seniors in North San Diego.",
    longDescription: "Pacific Crest Home Care is the go-to agency for dementia and memory care in North San Diego neighborhoods including La Jolla, University City, and Mira Mesa. Our memory-care-trained team uses structured activities, music therapy, and familiar routines to support cognitive wellness.",
    founded: 2017,
    licenseNumber: "CA-HCA-2017-011",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Fri: 8am–6pm",
  },
  {
    id: 15,
    name: "Harbor Senior Services",
    slug: "harbor-senior-services",
    city: "San Diego",
    citySlug: "san-diego",
    county: "San Diego County",
    state: "CA",
    zip: "92106",
    phone: "(619) 555-1505",
    address: "2390 Shelter Island Dr, San Diego, CA 92106",
    lat: 32.7074,
    lng: -117.2196,
    rating: 4.7,
    reviewCount: 46,
    services: ["Personal Care", "Meal Preparation", "Transportation", "Errands"],
    description: "Harbor Senior Services keeps seniors thriving in Point Loma and Ocean Beach with lifestyle support care.",
    longDescription: "Harbor Senior Services was founded by a retired Navy family to honor the veteran and military community of Point Loma and Shelter Island. We have significant experience caring for veterans with service-related conditions and navigating VA benefits for eligible clients.",
    founded: 2015,
    licenseNumber: "CA-HCA-2015-010",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sat: 7am–7pm",
  },
  {
    id: 16,
    name: "Sunrise Companion Care SD",
    slug: "sunrise-companion-care-sd",
    city: "San Diego",
    citySlug: "san-diego",
    county: "San Diego County",
    state: "CA",
    zip: "92115",
    phone: "(619) 555-1606",
    address: "6699 El Cajon Blvd, San Diego, CA 92115",
    lat: 32.7532,
    lng: -117.0731,
    rating: 4.5,
    reviewCount: 22,
    services: ["Companionship", "Respite Care", "Light Housekeeping"],
    description: "Sunrise Companion Care provides friendly, reliable companion and respite care in East San Diego.",
    longDescription: "Sunrise Companion Care SD brings warmth and consistent support to seniors in College Area, City Heights, and East San Diego. We specialize in matching seniors with companions who share their interests, creating genuine relationships that go beyond basic task completion.",
    founded: 2020,
    licenseNumber: "CA-HCA-2020-032",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Fri: 9am–5pm",
  },
  {
    id: 17,
    name: "TrueNorth Home Health",
    slug: "truenorth-home-health",
    city: "San Diego",
    citySlug: "san-diego",
    county: "San Diego County",
    state: "CA",
    zip: "92131",
    phone: "(858) 555-1707",
    address: "10455 Sorrento Valley Rd, San Diego, CA 92131",
    lat: 32.8892,
    lng: -117.1605,
    rating: 4.8,
    reviewCount: 58,
    services: ["Personal Care", "24-Hour Care", "Dementia Care", "Hospice Support"],
    description: "TrueNorth Home Health offers comprehensive in-home care across Scripps Ranch, Mira Mesa, and North County.",
    longDescription: "TrueNorth Home Health is a full-service home care agency operating across the entire San Diego metro area. With 24-hour care, specialized dementia support, and hospice coordination, TrueNorth is a trusted partner for families navigating complex care needs in Scripps Ranch, Mira Mesa, Rancho Bernardo, and beyond.",
    founded: 2013,
    licenseNumber: "CA-HCA-2013-007",
    featured: true,
    rxCarePartner: true,
    hours: "24/7 availability",
  },

  /* ---- Orange County (7) ---- */
  {
    id: 18,
    name: "OC Senior Solutions",
    slug: "oc-senior-solutions",
    city: "Irvine",
    citySlug: "irvine",
    county: "Orange County",
    state: "CA",
    zip: "92612",
    phone: "(949) 555-1801",
    address: "18101 Von Karman Ave, Irvine, CA 92612",
    lat: 33.6762,
    lng: -117.8437,
    rating: 4.9,
    reviewCount: 67,
    services: ["Personal Care", "Dementia Care", "24-Hour Care", "Companionship"],
    description: "OC Senior Solutions is Orange County's premier in-home care agency, based in Irvine.",
    longDescription: "OC Senior Solutions serves families across all of Orange County with premium personal care, dementia support, and 24-hour services. Headquartered in Irvine with coordinators throughout the county, we deliver fast response times and highly personalized care matches for every client.",
    founded: 2014,
    licenseNumber: "CA-HCA-2014-009",
    featured: true,
    rxCarePartner: true,
    hours: "24/7 availability",
  },
  {
    id: 19,
    name: "Newport Home Care Group",
    slug: "newport-home-care-group",
    city: "Anaheim",
    citySlug: "anaheim",
    county: "Orange County",
    state: "CA",
    zip: "92801",
    phone: "(714) 555-1902",
    address: "1600 W Lincoln Ave, Anaheim, CA 92801",
    lat: 33.8392,
    lng: -117.9167,
    rating: 4.7,
    reviewCount: 45,
    services: ["Personal Care", "Respite Care", "Medication Reminders"],
    description: "Newport Home Care Group delivers trusted personal care and respite services throughout northern Orange County.",
    longDescription: "Newport Home Care Group has built a strong reputation across northern Orange County by focusing on caregiver consistency and family communication. Our proprietary care-matching software ensures every client is paired with the right caregiver based on personality, skills, and availability.",
    founded: 2016,
    licenseNumber: "CA-HCA-2016-016",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sun: 7am–9pm",
  },
  {
    id: 20,
    name: "Saddleback Senior Care",
    slug: "saddleback-senior-care",
    city: "Anaheim",
    citySlug: "anaheim",
    county: "Orange County",
    state: "CA",
    zip: "92804",
    phone: "(714) 555-2003",
    address: "3245 W Ball Rd, Anaheim, CA 92804",
    lat: 33.8179,
    lng: -117.9568,
    rating: 4.6,
    reviewCount: 39,
    services: ["Personal Care", "Dementia Care", "Hospice Support", "Light Housekeeping"],
    description: "Saddleback Senior Care provides expert dementia and hospice support care in Anaheim and surrounding OC communities.",
    longDescription: "Saddleback Senior Care specializes in supporting families through dementia and end-of-life care with compassion and expertise. We work alongside local hospice agencies and medical providers to create integrated care plans that honor each client's wishes and family values.",
    founded: 2015,
    licenseNumber: "CA-HCA-2015-013",
    featured: false,
    rxCarePartner: true,
    hours: "Mon–Sun: 7am–8pm",
  },
  {
    id: 21,
    name: "Orange County Home Health Alliance",
    slug: "orange-county-home-health-alliance",
    city: "Anaheim",
    citySlug: "anaheim",
    county: "Orange County",
    state: "CA",
    zip: "92806",
    phone: "(714) 555-2101",
    address: "950 N Lemon St, Anaheim, CA 92806",
    lat: 33.8463,
    lng: -117.8766,
    rating: 4.5,
    reviewCount: 28,
    services: ["Personal Care", "24-Hour Care", "Companionship"],
    description: "Orange County Home Health Alliance offers affordable 24-hour and companion care across central Orange County.",
    longDescription: "Orange County Home Health Alliance was established to make quality in-home care accessible throughout central and North Orange County. We offer competitive hourly and live-in rates, no long-term contracts, and free care consultations to help families find the right level of support.",
    founded: 2019,
    licenseNumber: "CA-HCA-2019-024",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sun: 8am–8pm",
  },
  {
    id: 22,
    name: "South County Elder Care",
    slug: "south-county-elder-care",
    city: "Irvine",
    citySlug: "irvine",
    county: "Orange County",
    state: "CA",
    zip: "92618",
    phone: "(949) 555-2202",
    address: "15 Technology Dr, Irvine, CA 92618",
    lat: 33.6466,
    lng: -117.7378,
    rating: 4.7,
    reviewCount: 41,
    services: ["Dementia Care", "Personal Care", "Respite Care"],
    description: "South County Elder Care supports seniors and families in Irvine, Laguna Hills, and Mission Viejo.",
    longDescription: "South County Elder Care serves the growing senior population in South Orange County with specialized dementia care and flexible personal care schedules. Our coordinators in Irvine serve clients in Laguna Hills, Mission Viejo, Lake Forest, and Aliso Viejo with quick response times and personalized service.",
    founded: 2017,
    licenseNumber: "CA-HCA-2017-018",
    featured: false,
    rxCarePartner: true,
    hours: "Mon–Sat: 7am–7pm",
  },
  {
    id: 23,
    name: "Heritage Home Care",
    slug: "heritage-home-care",
    city: "Anaheim",
    citySlug: "anaheim",
    county: "Orange County",
    state: "CA",
    zip: "92832",
    phone: "(714) 555-2303",
    address: "2001 W Lincoln Ave, Anaheim, CA 92832",
    lat: 33.8412,
    lng: -117.9346,
    rating: 4.6,
    reviewCount: 34,
    services: ["Personal Care", "Meal Preparation", "Transportation", "Errands"],
    description: "Heritage Home Care offers bilingual Spanish-English care services in Anaheim and Fullerton.",
    longDescription: "Heritage Home Care proudly serves the Hispanic community of Anaheim and Fullerton with fully bilingual caregivers who understand cultural values, dietary preferences, and family dynamics. We offer flexible hourly and daily care starting at 4-hour minimum shifts.",
    founded: 2018,
    licenseNumber: "CA-HCA-2018-023",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sat: 7am–8pm",
  },
  {
    id: 24,
    name: "Pacific Home Companions",
    slug: "pacific-home-companions",
    city: "Irvine",
    citySlug: "irvine",
    county: "Orange County",
    state: "CA",
    zip: "92614",
    phone: "(949) 555-2404",
    address: "2102 Business Center Dr, Irvine, CA 92614",
    lat: 33.6601,
    lng: -117.8210,
    rating: 4.8,
    reviewCount: 53,
    services: ["Companionship", "Personal Care", "24-Hour Care", "Transportation"],
    description: "Pacific Home Companions pairs seniors with highly matched companions for lasting relationships and trusted care.",
    longDescription: "Pacific Home Companions is built on the belief that the right caregiver match changes everything. Our detailed intake process considers hobbies, personality, language preference, and care needs to create long-term caregiver-client relationships that go far beyond task completion. Serving South Orange County since 2013.",
    founded: 2013,
    licenseNumber: "CA-HCA-2013-008",
    featured: true,
    rxCarePartner: true,
    hours: "24/7 availability",
  },

  /* ---- Riverside (5) ---- */
  {
    id: 25,
    name: "Inland Empire Senior Care",
    slug: "inland-empire-senior-care",
    city: "Riverside",
    citySlug: "riverside",
    county: "Riverside County",
    state: "CA",
    zip: "92501",
    phone: "(951) 555-2501",
    address: "3880 Lemon St, Riverside, CA 92501",
    lat: 33.9806,
    lng: -117.3755,
    rating: 4.7,
    reviewCount: 48,
    services: ["Personal Care", "Dementia Care", "24-Hour Care"],
    description: "Inland Empire Senior Care is the leading home care provider serving Riverside and surrounding IE communities.",
    longDescription: "Inland Empire Senior Care has served Riverside County families for over a decade with reliable personal care, dementia support, and 24-hour coverage. We employ over 80 caregivers across Riverside, Corona, Norco, and Jurupa Valley to ensure fast placement and consistent service.",
    founded: 2012,
    licenseNumber: "CA-HCA-2012-011",
    featured: true,
    rxCarePartner: true,
    hours: "24/7 availability",
  },
  {
    id: 26,
    name: "Desert Springs Home Health",
    slug: "desert-springs-home-health",
    city: "Riverside",
    citySlug: "riverside",
    county: "Riverside County",
    state: "CA",
    zip: "92507",
    phone: "(951) 555-2602",
    address: "6400 Magnolia Ave, Riverside, CA 92507",
    lat: 33.9484,
    lng: -117.3356,
    rating: 4.6,
    reviewCount: 36,
    services: ["Personal Care", "Respite Care", "Companionship"],
    description: "Desert Springs Home Health delivers warm, attentive care to seniors in east Riverside and Moreno Valley.",
    longDescription: "Desert Springs Home Health understands the unique challenges of caring for seniors in the warmer Inland climate. Our caregivers are trained in heat-safety protocols, hydration management, and creating comfortable environments year-round for seniors in Riverside, Moreno Valley, and Perris.",
    founded: 2017,
    licenseNumber: "CA-HCA-2017-021",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sun: 7am–8pm",
  },
  {
    id: 27,
    name: "Crown City Senior Care",
    slug: "crown-city-senior-care",
    city: "Riverside",
    citySlug: "riverside",
    county: "Riverside County",
    state: "CA",
    zip: "92503",
    phone: "(951) 555-2703",
    address: "2250 Iowa Ave, Riverside, CA 92503",
    lat: 33.9918,
    lng: -117.4210,
    rating: 4.5,
    reviewCount: 27,
    services: ["Dementia Care", "Hospice Support", "Personal Care"],
    description: "Crown City Senior Care specializes in dementia and hospice support care across northwest Riverside.",
    longDescription: "Crown City Senior Care was founded by a former hospital social worker who saw families struggling to navigate end-of-life and memory care at home. We bring structured, evidence-based dementia care and dignified hospice companion support to northwest Riverside County.",
    founded: 2019,
    licenseNumber: "CA-HCA-2019-027",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sat: 8am–7pm",
  },
  {
    id: 28,
    name: "Citrus Valley Home Care",
    slug: "citrus-valley-home-care",
    city: "Riverside",
    citySlug: "riverside",
    county: "Riverside County",
    state: "CA",
    zip: "92570",
    phone: "(951) 555-2804",
    address: "1540 Center St, Norco, CA 92560",
    lat: 33.9278,
    lng: -117.5519,
    rating: 4.6,
    reviewCount: 32,
    services: ["Personal Care", "Meal Preparation", "Transportation", "Light Housekeeping"],
    description: "Citrus Valley Home Care serves Norco, Corona, and eastern Riverside with comprehensive daily living assistance.",
    longDescription: "Citrus Valley Home Care has been a community fixture in Norco and Corona since 2016. We understand the rural and semi-rural character of eastern Riverside County and provide reliable transportation, meal prep, and personal care for seniors who may live far from medical facilities.",
    founded: 2016,
    licenseNumber: "CA-HCA-2016-024",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Fri: 7am–6pm",
  },
  {
    id: 29,
    name: "Riverside Elder Services",
    slug: "riverside-elder-services",
    city: "Riverside",
    citySlug: "riverside",
    county: "Riverside County",
    state: "CA",
    zip: "92505",
    phone: "(951) 555-2905",
    address: "7851 Mission Blvd, Riverside, CA 92509",
    lat: 33.9750,
    lng: -117.3947,
    rating: 4.7,
    reviewCount: 44,
    services: ["Personal Care", "24-Hour Care", "Companionship", "Medication Reminders"],
    description: "Riverside Elder Services provides dependable 24-hour care and medication reminders throughout Riverside County.",
    longDescription: "Riverside Elder Services supports seniors who need consistent daily care management including medication reminders, personal hygiene assistance, and overnight monitoring. Our care managers conduct quarterly assessments to ensure care plans evolve with each client's changing health needs.",
    founded: 2014,
    licenseNumber: "CA-HCA-2014-017",
    featured: false,
    rxCarePartner: true,
    hours: "24/7 availability",
  },

  /* ---- San Bernardino (4) ---- */
  {
    id: 30,
    name: "High Desert Home Care",
    slug: "high-desert-home-care",
    city: "San Bernardino",
    citySlug: "san-bernardino",
    county: "San Bernardino County",
    state: "CA",
    zip: "92401",
    phone: "(909) 555-3001",
    address: "285 E Hospitality Ln, San Bernardino, CA 92408",
    lat: 34.0608,
    lng: -117.2898,
    rating: 4.6,
    reviewCount: 33,
    services: ["Personal Care", "Dementia Care", "Companionship"],
    description: "High Desert Home Care serves San Bernardino, Fontana, and the High Desert with trusted in-home care.",
    longDescription: "High Desert Home Care provides reliable in-home care for seniors across San Bernardino, Fontana, Rialto, and the High Desert communities of Victorville and Apple Valley. We are the only agency in the area with a dedicated bilingual care coordinator for Spanish-speaking families.",
    founded: 2015,
    licenseNumber: "CA-HCA-2015-016",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sun: 7am–8pm",
  },
  {
    id: 31,
    name: "Arrowhead Elder Care",
    slug: "arrowhead-elder-care",
    city: "San Bernardino",
    citySlug: "san-bernardino",
    county: "San Bernardino County",
    state: "CA",
    zip: "92404",
    phone: "(909) 555-3102",
    address: "1990 N Waterman Ave, San Bernardino, CA 92404",
    lat: 34.1231,
    lng: -117.2703,
    rating: 4.5,
    reviewCount: 26,
    services: ["Personal Care", "24-Hour Care", "Respite Care"],
    description: "Arrowhead Elder Care provides personal and 24-hour care for seniors in North San Bernardino and mountain communities.",
    longDescription: "Arrowhead Elder Care serves both valley and mountain communities in San Bernardino County, including Lake Arrowhead and Big Bear residents who spend time in the valley. We understand the logistical challenges of mountain living and offer flexible scheduling for seasonal residents.",
    founded: 2018,
    licenseNumber: "CA-HCA-2018-025",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sat: 7am–7pm",
  },
  {
    id: 32,
    name: "Redlands Senior Solutions",
    slug: "redlands-senior-solutions",
    city: "San Bernardino",
    citySlug: "san-bernardino",
    county: "San Bernardino County",
    state: "CA",
    zip: "92374",
    phone: "(909) 555-3203",
    address: "420 W State St, Redlands, CA 92373",
    lat: 34.0556,
    lng: -117.1826,
    rating: 4.7,
    reviewCount: 39,
    services: ["Personal Care", "Dementia Care", "Transportation", "Meal Preparation"],
    description: "Redlands Senior Solutions provides dignified, community-centered home care in Redlands and Loma Linda.",
    longDescription: "Redlands Senior Solutions was founded by a husband-and-wife team with backgrounds in nursing and social work. We are deeply embedded in the Redlands and Loma Linda communities, partnering with Loma Linda University Medical Center and local faith communities to connect seniors with the care they need.",
    founded: 2016,
    licenseNumber: "CA-HCA-2016-020",
    featured: false,
    rxCarePartner: true,
    hours: "Mon–Fri: 8am–6pm",
  },
  {
    id: 33,
    name: "Mountain View Home Health",
    slug: "mountain-view-home-health",
    city: "San Bernardino",
    citySlug: "san-bernardino",
    county: "San Bernardino County",
    state: "CA",
    zip: "92346",
    phone: "(909) 555-3304",
    address: "1410 E Washington St, Colton, CA 92324",
    lat: 34.0738,
    lng: -117.3120,
    rating: 4.5,
    reviewCount: 22,
    services: ["Personal Care", "Companionship", "Light Housekeeping"],
    description: "Mountain View Home Health serves Colton, Grand Terrace, and Bloomington with affordable personal care.",
    longDescription: "Mountain View Home Health is committed to making quality home care accessible in underserved communities of western San Bernardino County. We work with families on flexible payment plans and help navigate long-term care insurance claims and other funding sources.",
    founded: 2020,
    licenseNumber: "CA-HCA-2020-033",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Fri: 8am–5pm",
  },

  /* ---- Long Beach (3) ---- */
  {
    id: 34,
    name: "Shoreline Senior Care",
    slug: "shoreline-senior-care",
    city: "Long Beach",
    citySlug: "long-beach",
    county: "Los Angeles County",
    state: "CA",
    zip: "90802",
    phone: "(562) 555-3401",
    address: "111 W Ocean Blvd, Long Beach, CA 90802",
    lat: 33.7701,
    lng: -118.1937,
    rating: 4.8,
    reviewCount: 54,
    services: ["Personal Care", "24-Hour Care", "Dementia Care", "Companionship"],
    description: "Shoreline Senior Care is Long Beach's most trusted in-home care agency, serving all Long Beach neighborhoods.",
    longDescription: "Shoreline Senior Care has been Long Beach's preferred in-home care agency since 2013. With deep roots in the community and partnerships with Long Beach Memorial Medical Center, Shoreline delivers seamless hospital-to-home transitions and ongoing care for seniors throughout the city.",
    founded: 2013,
    licenseNumber: "CA-HCA-2013-009",
    featured: true,
    rxCarePartner: true,
    hours: "24/7 availability",
  },
  {
    id: 35,
    name: "Harbor Home Health",
    slug: "harbor-home-health",
    city: "Long Beach",
    citySlug: "long-beach",
    county: "Los Angeles County",
    state: "CA",
    zip: "90810",
    phone: "(562) 555-3502",
    address: "2640 Long Beach Blvd, Long Beach, CA 90806",
    lat: 33.8128,
    lng: -118.1869,
    rating: 4.6,
    reviewCount: 37,
    services: ["Personal Care", "Respite Care", "Meal Preparation"],
    description: "Harbor Home Health delivers reliable respite and personal care throughout West Long Beach and Signal Hill.",
    longDescription: "Harbor Home Health provides essential daily support and respite care for families in West Long Beach, Signal Hill, and Wilmington. We offer bilingual (English/Spanish/Khmer) services and are a culturally informed care provider for Long Beach's diverse senior population.",
    founded: 2017,
    licenseNumber: "CA-HCA-2017-023",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sat: 7am–8pm",
  },
  {
    id: 36,
    name: "Long Beach Elder Care Partners",
    slug: "long-beach-elder-care-partners",
    city: "Long Beach",
    citySlug: "long-beach",
    county: "Los Angeles County",
    state: "CA",
    zip: "90815",
    phone: "(562) 555-3603",
    address: "5450 E Stearns St, Long Beach, CA 90815",
    lat: 33.7864,
    lng: -118.1152,
    rating: 4.7,
    reviewCount: 41,
    services: ["Dementia Care", "Personal Care", "Transportation"],
    description: "Long Beach Elder Care Partners focuses on dementia care and mobility support in East Long Beach.",
    longDescription: "Long Beach Elder Care Partners serves seniors in East Long Beach, Lakewood, and Seal Beach with specialized dementia care and comprehensive mobility support. We partner with local neurologists and geriatric care managers to provide medically-informed non-medical care plans.",
    founded: 2015,
    licenseNumber: "CA-HCA-2015-018",
    featured: false,
    rxCarePartner: true,
    hours: "Mon–Sun: 7am–9pm",
  },

  /* ---- Pasadena (3) ---- */
  {
    id: 37,
    name: "Pasadena Senior Care Group",
    slug: "pasadena-senior-care-group",
    city: "Pasadena",
    citySlug: "pasadena",
    county: "Los Angeles County",
    state: "CA",
    zip: "91101",
    phone: "(626) 555-3701",
    address: "300 E Colorado Blvd, Pasadena, CA 91101",
    lat: 34.1469,
    lng: -118.1426,
    rating: 4.8,
    reviewCount: 57,
    services: ["Personal Care", "Dementia Care", "24-Hour Care"],
    description: "Pasadena Senior Care Group is the premier home care agency for Pasadena and San Gabriel Valley seniors.",
    longDescription: "Pasadena Senior Care Group brings clinical-quality non-medical care to seniors in Pasadena, Arcadia, Monrovia, and the greater San Gabriel Valley. Our owner is a licensed clinical social worker who built the agency on evidence-based care practices and a deep commitment to aging-in-place success.",
    founded: 2012,
    licenseNumber: "CA-HCA-2012-012",
    featured: true,
    rxCarePartner: true,
    hours: "24/7 availability",
  },
  {
    id: 38,
    name: "San Gabriel Valley Home Health",
    slug: "san-gabriel-valley-home-health",
    city: "Pasadena",
    citySlug: "pasadena",
    county: "Los Angeles County",
    state: "CA",
    zip: "91107",
    phone: "(626) 555-3802",
    address: "2200 E Foothill Blvd, Pasadena, CA 91107",
    lat: 34.1572,
    lng: -118.0869,
    rating: 4.6,
    reviewCount: 34,
    services: ["Personal Care", "Companionship", "Transportation", "Meal Preparation"],
    description: "San Gabriel Valley Home Health serves Asian-American seniors with culturally attuned care in the East San Gabriel Valley.",
    longDescription: "San Gabriel Valley Home Health offers Mandarin-, Cantonese-, and Korean-speaking caregivers to serve the East San Gabriel Valley's large Asian-American senior population in Arcadia, Alhambra, Monterey Park, and Rosemead. We honor dietary, cultural, and communication preferences unique to each family.",
    founded: 2016,
    licenseNumber: "CA-HCA-2016-026",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sat: 8am–7pm",
  },
  {
    id: 39,
    name: "Foothill Elder Care Services",
    slug: "foothill-elder-care-services",
    city: "Pasadena",
    citySlug: "pasadena",
    county: "Los Angeles County",
    state: "CA",
    zip: "91103",
    phone: "(626) 555-3903",
    address: "1440 N Lake Ave, Pasadena, CA 91104",
    lat: 34.1736,
    lng: -118.1317,
    rating: 4.7,
    reviewCount: 43,
    services: ["Personal Care", "Respite Care", "Medication Reminders", "Hospice Support"],
    description: "Foothill Elder Care Services specializes in respite and hospice companion care in North Pasadena and Altadena.",
    longDescription: "Foothill Elder Care Services brings expert respite and end-of-life companion care to North Pasadena, Altadena, and Sierra Madre. Our hospice-support caregivers complete 40+ hours of specialized training and receive ongoing supervision from registered nurses to ensure the highest standard of compassionate care.",
    founded: 2014,
    licenseNumber: "CA-HCA-2014-019",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sun: 7am–9pm",
  },

  /* ---- Santa Ana (3) ---- */
  {
    id: 40,
    name: "Santa Ana Home Care Network",
    slug: "santa-ana-home-care-network",
    city: "Santa Ana",
    citySlug: "santa-ana",
    county: "Orange County",
    state: "CA",
    zip: "92701",
    phone: "(714) 555-4001",
    address: "1600 N Main St, Santa Ana, CA 92701",
    lat: 33.7628,
    lng: -117.8691,
    rating: 4.7,
    reviewCount: 46,
    services: ["Personal Care", "Dementia Care", "Companionship", "Transportation"],
    description: "Santa Ana Home Care Network provides bilingual in-home care for seniors throughout central Orange County.",
    longDescription: "Santa Ana Home Care Network is a family-owned bilingual (English/Spanish) agency deeply rooted in the Santa Ana community. We serve seniors in Santa Ana, Garden Grove, and Westminster with culturally respectful care that honors family values, traditions, and communication preferences.",
    founded: 2014,
    licenseNumber: "CA-HCA-2014-021",
    featured: false,
    rxCarePartner: true,
    hours: "Mon–Sun: 7am–8pm",
  },
  {
    id: 41,
    name: "Central OC Senior Services",
    slug: "central-oc-senior-services",
    city: "Santa Ana",
    citySlug: "santa-ana",
    county: "Orange County",
    state: "CA",
    zip: "92703",
    phone: "(714) 555-4102",
    address: "2001 W 5th St, Santa Ana, CA 92703",
    lat: 33.7512,
    lng: -117.8887,
    rating: 4.5,
    reviewCount: 29,
    services: ["Personal Care", "Respite Care", "Light Housekeeping"],
    description: "Central OC Senior Services delivers flexible, affordable personal care and housekeeping in Santa Ana and Fountain Valley.",
    longDescription: "Central OC Senior Services was founded with a mission to make quality care accessible for working-class families in central Orange County. We offer pay-as-you-go hourly care with no long-term commitments and flexible scheduling that adapts to each family's schedule and budget.",
    founded: 2019,
    licenseNumber: "CA-HCA-2019-028",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sat: 8am–6pm",
  },
  {
    id: 42,
    name: "First Coast Home Care",
    slug: "first-coast-home-care",
    city: "Santa Ana",
    citySlug: "santa-ana",
    county: "Orange County",
    state: "CA",
    zip: "92705",
    phone: "(714) 555-4203",
    address: "3333 S Bristol St, Santa Ana, CA 92704",
    lat: 33.7267,
    lng: -117.8876,
    rating: 4.6,
    reviewCount: 38,
    services: ["Personal Care", "24-Hour Care", "Medication Reminders", "Meal Preparation"],
    description: "First Coast Home Care offers 24-hour care and medication management for seniors in South Santa Ana and Tustin.",
    longDescription: "First Coast Home Care serves seniors in South Santa Ana, Tustin, and North Orange County with comprehensive daily care including medication reminders, meal preparation, and overnight monitoring. Our registered nurse care manager oversees all care plans and is available for family consultations.",
    founded: 2016,
    licenseNumber: "CA-HCA-2016-027",
    featured: false,
    rxCarePartner: false,
    hours: "24/7 availability",
  },

  /* ---- Irvine (3 additional) ---- */
  {
    id: 43,
    name: "Irvine Home Health Partners",
    slug: "irvine-home-health-partners",
    city: "Irvine",
    citySlug: "irvine",
    county: "Orange County",
    state: "CA",
    zip: "92620",
    phone: "(949) 555-4301",
    address: "4 Park Plaza, Suite 100, Irvine, CA 92614",
    lat: 33.6875,
    lng: -117.8261,
    rating: 4.8,
    reviewCount: 61,
    services: ["Personal Care", "Dementia Care", "Companionship", "Respite Care"],
    description: "Irvine Home Health Partners is an award-winning home care agency serving Irvine and all of South OC.",
    longDescription: "Irvine Home Health Partners has won the Best of Irvine award three years running for outstanding home care services. Our team of 120+ caregivers serves all Irvine ZIP codes and surrounding communities with same-day care placement in most cases. We offer a unique care guarantee: if you're not satisfied with your first caregiver match, we'll replace them for free.",
    founded: 2011,
    licenseNumber: "CA-HCA-2011-004",
    featured: true,
    rxCarePartner: true,
    hours: "24/7 availability",
  },
  {
    id: 44,
    name: "University Park Senior Care",
    slug: "university-park-senior-care",
    city: "Irvine",
    citySlug: "irvine",
    county: "Orange County",
    state: "CA",
    zip: "92612",
    phone: "(949) 555-4402",
    address: "5600 Alton Pkwy, Irvine, CA 92618",
    lat: 33.6547,
    lng: -117.7453,
    rating: 4.6,
    reviewCount: 35,
    services: ["Companionship", "Transportation", "Medication Reminders"],
    description: "University Park Senior Care provides friendly companion care and transportation for active seniors in Irvine.",
    longDescription: "University Park Senior Care focuses on enabling independence for seniors who need light support services. We specialize in accompanying seniors to UCI Medical appointments, errands, and social activities—helping seniors stay connected to the community while receiving professional support.",
    founded: 2018,
    licenseNumber: "CA-HCA-2018-029",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Fri: 8am–6pm",
  },
  {
    id: 45,
    name: "Woodbridge Elder Services",
    slug: "woodbridge-elder-services",
    city: "Irvine",
    citySlug: "irvine",
    county: "Orange County",
    state: "CA",
    zip: "92604",
    phone: "(949) 555-4503",
    address: "2 Shea Center Dr, Irvine, CA 92618",
    lat: 33.6821,
    lng: -117.7895,
    rating: 4.7,
    reviewCount: 48,
    services: ["Personal Care", "Dementia Care", "24-Hour Care", "Hospice Support"],
    description: "Woodbridge Elder Services provides comprehensive senior care in Irvine's Woodbridge and Northwood villages.",
    longDescription: "Woodbridge Elder Services is a community-focused agency serving the planned village neighborhoods of Irvine. Our caregivers are matched by village proximity to minimize travel time and ensure familiarity with each client's neighborhood. We provide personal care, dementia support, and full 24-hour live-in services.",
    founded: 2015,
    licenseNumber: "CA-HCA-2015-022",
    featured: false,
    rxCarePartner: true,
    hours: "Mon–Sun: 7am–10pm",
  },

  /* ---- Fresno (3) ---- */
  {
    id: 46,
    name: "Central Valley Home Care",
    slug: "central-valley-home-care",
    city: "Fresno",
    citySlug: "fresno",
    county: "Fresno County",
    state: "CA",
    zip: "93720",
    phone: "(559) 555-4601",
    address: "7625 N Palm Ave, Fresno, CA 93711",
    lat: 36.8122,
    lng: -119.7871,
    rating: 4.7,
    reviewCount: 44,
    services: ["Personal Care", "Dementia Care", "24-Hour Care"],
    description: "Central Valley Home Care is Fresno's most established in-home senior care agency, serving the Valley since 2010.",
    longDescription: "Central Valley Home Care has been caring for Fresno County seniors for over 15 years. As the Central Valley's population of aging adults grows, we have expanded our team to over 200 caregivers serving Fresno, Clovis, and surrounding communities with full personal care, dementia support, and round-the-clock coverage.",
    founded: 2010,
    licenseNumber: "CA-HCA-2010-001",
    featured: true,
    rxCarePartner: true,
    hours: "24/7 availability",
  },
  {
    id: 47,
    name: "Fresno Senior Solutions",
    slug: "fresno-senior-solutions",
    city: "Fresno",
    citySlug: "fresno",
    county: "Fresno County",
    state: "CA",
    zip: "93706",
    phone: "(559) 555-4702",
    address: "4444 E Kings Canyon Rd, Fresno, CA 93702",
    lat: 36.7325,
    lng: -119.7526,
    rating: 4.5,
    reviewCount: 28,
    services: ["Personal Care", "Respite Care", "Meal Preparation", "Companionship"],
    description: "Fresno Senior Solutions provides affordable daily care and companionship for seniors across southeast Fresno.",
    longDescription: "Fresno Senior Solutions serves the diverse senior community of southeast Fresno and the neighboring Sanger and Reedley areas. We offer bilingual English/Spanish and English/Hmong care coordination and have strong ties to Fresno County's aging services network.",
    founded: 2018,
    licenseNumber: "CA-HCA-2018-030",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sat: 7am–7pm",
  },
  {
    id: 48,
    name: "Valley Oaks Elder Care",
    slug: "valley-oaks-elder-care",
    city: "Fresno",
    citySlug: "fresno",
    county: "Fresno County",
    state: "CA",
    zip: "93720",
    phone: "(559) 555-4803",
    address: "7680 N Ingram Ave, Fresno, CA 93711",
    lat: 36.8140,
    lng: -119.8014,
    rating: 4.6,
    reviewCount: 33,
    services: ["Dementia Care", "Personal Care", "Transportation", "Light Housekeeping"],
    description: "Valley Oaks Elder Care specializes in dementia care and mobility support for seniors in north Fresno and Clovis.",
    longDescription: "Valley Oaks Elder Care brings specialized dementia care and mobility support to seniors in north Fresno, Clovis, and the surrounding foothills communities. Our founders both have personal experience with dementia caregiving in their own families, which drives our deep empathy and expertise in memory care.",
    founded: 2016,
    licenseNumber: "CA-HCA-2016-028",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Fri: 8am–6pm",
  },

  /* ---- Sacramento (2) ---- */
  {
    id: 49,
    name: "Capital City Senior Care",
    slug: "capital-city-senior-care",
    city: "Sacramento",
    citySlug: "sacramento",
    county: "Sacramento County",
    state: "CA",
    zip: "95825",
    phone: "(916) 555-4901",
    address: "1400 Arden Way, Sacramento, CA 95825",
    lat: 38.5967,
    lng: -121.4093,
    rating: 4.8,
    reviewCount: 59,
    services: ["Personal Care", "Dementia Care", "24-Hour Care", "Respite Care"],
    description: "Capital City Senior Care provides comprehensive in-home care throughout the Sacramento metro area.",
    longDescription: "Capital City Senior Care serves the Sacramento metropolitan area with a full suite of non-medical home care services. As one of Sacramento's larger independent agencies, we have placement capacity for urgent care requests and offer care coordination for seniors transitioning from hospital or skilled nursing facilities.",
    founded: 2013,
    licenseNumber: "CA-HCA-2013-010",
    featured: true,
    rxCarePartner: true,
    hours: "24/7 availability",
  },
  {
    id: 50,
    name: "River City Elder Services",
    slug: "river-city-elder-services",
    city: "Sacramento",
    citySlug: "sacramento",
    county: "Sacramento County",
    state: "CA",
    zip: "95816",
    phone: "(916) 555-5002",
    address: "2901 K St, Sacramento, CA 95816",
    lat: 38.5763,
    lng: -121.4829,
    rating: 4.6,
    reviewCount: 37,
    services: ["Personal Care", "Companionship", "Transportation", "Meal Preparation"],
    description: "River City Elder Services delivers companion and daily support care in Midtown, Land Park, and East Sacramento.",
    longDescription: "River City Elder Services is an intimate, owner-operated agency in Sacramento's historic Midtown and Land Park neighborhoods. We work exclusively with the most carefully screened caregivers and maintain small client-to-caregiver ratios to ensure highly personalized care and genuine human connection.",
    founded: 2017,
    licenseNumber: "CA-HCA-2017-033",
    featured: false,
    rxCarePartner: false,
    hours: "Mon–Sat: 8am–6pm",
  },
];

/* ------------------------------------------------------------------
   CALIFORNIA CITY KEYWORD MAP
   Used to generate SEO meta tags, page titles, and schema markup
   for each city directory page.
   ------------------------------------------------------------------ */
const CA_CITIES = {
  "los-angeles": {
    name: "Los Angeles",
    displayName: "Los Angeles, CA",
    county: "Los Angeles County",
    state: "California",
    stateAbbr: "CA",
    population: 3979576,
    lat: 34.0522,
    lng: -118.2437,
    metaTitle: "Home Care Agencies in Los Angeles, CA | RennXCare",
    metaDescription: "Find top-rated home care agencies in Los Angeles, California. Compare dementia care, 24-hour care, companion care, and personal care services near you. Free match in 24 hours.",
    h1: "Best Home Care Agencies in Los Angeles, California",
    intro: "Los Angeles families trust RennXCare to connect them with vetted, compassionate home care agencies. Whether you need dementia care in the Valley, 24-hour support on the Westside, or companion care in South LA, find the right match here.",
    primaryKeywords: ["home care agencies Los Angeles", "in-home care LA", "senior care Los Angeles CA", "elder care Los Angeles"],
    longTailKeywords: ["home care agencies near me Los Angeles", "dementia care Los Angeles", "24-hour home care Los Angeles", "companion care Los Angeles senior"],
    neighborhoods: ["Hollywood", "Silver Lake", "Culver City", "Santa Monica", "Van Nuys", "Pasadena adjacent", "Koreatown", "Eagle Rock"],
  },
  "san-diego": {
    name: "San Diego",
    displayName: "San Diego, CA",
    county: "San Diego County",
    state: "California",
    stateAbbr: "CA",
    population: 1386932,
    lat: 32.7157,
    lng: -117.1611,
    metaTitle: "Home Care Agencies in San Diego, CA | RennXCare",
    metaDescription: "Find trusted home care agencies in San Diego, California. Compare services, read reviews, and connect with background-checked caregivers near you.",
    h1: "Best Home Care Agencies in San Diego, California",
    intro: "San Diego families deserve compassionate, professional home care. Browse RennXCare's directory of verified home care agencies across all San Diego neighborhoods—from downtown and Mission Hills to La Jolla and Chula Vista.",
    primaryKeywords: ["home care agencies San Diego", "in-home care San Diego", "senior care San Diego CA", "elder care San Diego"],
    longTailKeywords: ["home care agencies near me San Diego", "dementia care San Diego", "24-hour home care San Diego", "respite care San Diego"],
    neighborhoods: ["Mission Hills", "North Park", "La Jolla", "Coronado", "Point Loma", "Scripps Ranch", "East San Diego"],
  },
  "irvine": {
    name: "Irvine",
    displayName: "Irvine, CA",
    county: "Orange County",
    state: "California",
    stateAbbr: "CA",
    population: 307670,
    lat: 33.6846,
    lng: -117.8265,
    metaTitle: "Home Care Agencies in Irvine, CA | RennXCare",
    metaDescription: "Find top home care agencies in Irvine, California. Compare dementia, companion, and personal care services from vetted Orange County agencies.",
    h1: "Best Home Care Agencies in Irvine, California",
    intro: "Irvine's growing senior population deserves the best. Compare highly rated home care agencies in Irvine serving Woodbridge, Northwood, University Park, and all Irvine communities.",
    primaryKeywords: ["home care agencies Irvine", "in-home care Irvine CA", "senior care Irvine", "elder care Irvine Orange County"],
    longTailKeywords: ["home care near me Irvine", "dementia care Irvine CA", "24-hour home care Irvine", "companion care Irvine senior"],
    neighborhoods: ["Woodbridge", "Northwood", "University Park", "Westpark", "Quail Hill", "Turtle Rock"],
  },
  "anaheim": {
    name: "Anaheim",
    displayName: "Anaheim, CA",
    county: "Orange County",
    state: "California",
    stateAbbr: "CA",
    population: 346824,
    lat: 33.8366,
    lng: -117.9143,
    metaTitle: "Home Care Agencies in Anaheim, CA | RennXCare",
    metaDescription: "Find trusted home care agencies in Anaheim, California. Compare dementia, 24-hour, and personal care services across northern Orange County.",
    h1: "Best Home Care Agencies in Anaheim, California",
    intro: "Anaheim families can count on RennXCare to find qualified, background-checked home care agencies. Browse providers serving all Anaheim neighborhoods including Hills, Colony, and Platinum Triangle.",
    primaryKeywords: ["home care agencies Anaheim", "in-home care Anaheim CA", "senior care Anaheim", "elder care Anaheim OC"],
    longTailKeywords: ["home care near me Anaheim", "dementia care Anaheim CA", "24-hour home care Anaheim", "bilingual home care Anaheim"],
    neighborhoods: ["Anaheim Hills", "Colony", "Disneyland area", "East Anaheim", "North Anaheim"],
  },
  "riverside": {
    name: "Riverside",
    displayName: "Riverside, CA",
    county: "Riverside County",
    state: "California",
    stateAbbr: "CA",
    population: 314998,
    lat: 33.9806,
    lng: -117.3755,
    metaTitle: "Home Care Agencies in Riverside, CA | RennXCare",
    metaDescription: "Find home care agencies in Riverside, California. Compare senior care, dementia support, and 24-hour in-home care services in the Inland Empire.",
    h1: "Best Home Care Agencies in Riverside, California",
    intro: "Find reliable in-home care across Riverside and the Inland Empire. RennXCare connects families with vetted agencies providing personal care, dementia support, and round-the-clock assistance.",
    primaryKeywords: ["home care agencies Riverside", "in-home care Riverside CA", "senior care Riverside", "elder care Inland Empire"],
    longTailKeywords: ["home care near me Riverside CA", "dementia care Riverside", "24-hour care Riverside CA", "in-home senior care Riverside County"],
    neighborhoods: ["Canyon Crest", "La Sierra", "Victoria", "Woodcrest", "Orangecrest"],
  },
  "san-bernardino": {
    name: "San Bernardino",
    displayName: "San Bernardino, CA",
    county: "San Bernardino County",
    state: "California",
    stateAbbr: "CA",
    population: 222101,
    lat: 34.1083,
    lng: -117.2898,
    metaTitle: "Home Care Agencies in San Bernardino, CA | RennXCare",
    metaDescription: "Find home care agencies in San Bernardino, California. Compare personal care, dementia support, and in-home senior care services across San Bernardino County.",
    h1: "Best Home Care Agencies in San Bernardino, California",
    intro: "San Bernardino County seniors deserve quality in-home care close to home. Browse RennXCare's directory of verified agencies serving San Bernardino, Fontana, Redlands, and surrounding communities.",
    primaryKeywords: ["home care agencies San Bernardino", "in-home care San Bernardino CA", "senior care San Bernardino", "elder care Inland Empire"],
    longTailKeywords: ["home care near me San Bernardino", "dementia care San Bernardino", "bilingual home care San Bernardino", "in-home care Fontana CA"],
    neighborhoods: ["Highland", "Rialto area", "Fontana", "Redlands", "Colton"],
  },
  "long-beach": {
    name: "Long Beach",
    displayName: "Long Beach, CA",
    county: "Los Angeles County",
    state: "California",
    stateAbbr: "CA",
    population: 466742,
    lat: 33.7701,
    lng: -118.1937,
    metaTitle: "Home Care Agencies in Long Beach, CA | RennXCare",
    metaDescription: "Find trusted home care agencies in Long Beach, California. Compare personal care, dementia support, and companion care services near you.",
    h1: "Best Home Care Agencies in Long Beach, California",
    intro: "Long Beach families trust RennXCare to connect them with compassionate, qualified home care agencies. Browse providers across all Long Beach neighborhoods from Belmont Shore to Bixby Knolls.",
    primaryKeywords: ["home care agencies Long Beach", "in-home care Long Beach CA", "senior care Long Beach", "elder care Long Beach"],
    longTailKeywords: ["home care near me Long Beach CA", "dementia care Long Beach", "24-hour home care Long Beach", "bilingual home care Long Beach"],
    neighborhoods: ["Belmont Shore", "Bixby Knolls", "Signal Hill", "East Long Beach", "West Long Beach"],
  },
  "pasadena": {
    name: "Pasadena",
    displayName: "Pasadena, CA",
    county: "Los Angeles County",
    state: "California",
    stateAbbr: "CA",
    population: 141029,
    lat: 34.1478,
    lng: -118.1445,
    metaTitle: "Home Care Agencies in Pasadena, CA | RennXCare",
    metaDescription: "Find top home care agencies in Pasadena, California. Compare dementia care, personal care, and respite services in the San Gabriel Valley.",
    h1: "Best Home Care Agencies in Pasadena, California",
    intro: "Pasadena families can rely on RennXCare to find the right in-home care match. Browse highly rated agencies serving Pasadena, Altadena, San Marino, and the greater San Gabriel Valley.",
    primaryKeywords: ["home care agencies Pasadena", "in-home care Pasadena CA", "senior care Pasadena", "elder care San Gabriel Valley"],
    longTailKeywords: ["home care near me Pasadena CA", "dementia care Pasadena", "respite care Pasadena CA", "caregiver jobs Pasadena CA"],
    neighborhoods: ["Altadena", "San Marino", "East Pasadena", "Arcadia", "Monrovia"],
  },
  "santa-ana": {
    name: "Santa Ana",
    displayName: "Santa Ana, CA",
    county: "Orange County",
    state: "California",
    stateAbbr: "CA",
    population: 310227,
    lat: 33.7454,
    lng: -117.8677,
    metaTitle: "Home Care Agencies in Santa Ana, CA | RennXCare",
    metaDescription: "Find home care agencies in Santa Ana, California. Compare bilingual Spanish-English personal care, dementia, and companion care services in central Orange County.",
    h1: "Best Home Care Agencies in Santa Ana, California",
    intro: "Santa Ana's diverse community deserves culturally attuned, bilingual home care. Browse RennXCare's directory of agencies providing Spanish-English and other multilingual senior care services.",
    primaryKeywords: ["home care agencies Santa Ana", "in-home care Santa Ana CA", "senior care Santa Ana", "bilingual home care Orange County"],
    longTailKeywords: ["home care near me Santa Ana", "demencia care Santa Ana", "cuidado en casa Santa Ana", "senior care Garden Grove"],
    neighborhoods: ["Midway City", "Garden Grove", "Westminster", "Fountain Valley"],
  },
  "fresno": {
    name: "Fresno",
    displayName: "Fresno, CA",
    county: "Fresno County",
    state: "California",
    stateAbbr: "CA",
    population: 542107,
    lat: 36.7378,
    lng: -119.7871,
    metaTitle: "Home Care Agencies in Fresno, CA | RennXCare",
    metaDescription: "Find home care agencies in Fresno, California. Compare personal care, dementia support, and in-home senior care in the Central Valley.",
    h1: "Best Home Care Agencies in Fresno, California",
    intro: "Fresno County's senior population is growing fast. Compare RennXCare's verified home care agencies across Fresno, Clovis, and surrounding Central Valley communities.",
    primaryKeywords: ["home care agencies Fresno", "in-home care Fresno CA", "senior care Fresno", "elder care Central Valley"],
    longTailKeywords: ["home care near me Fresno CA", "dementia care Fresno", "24-hour home care Fresno", "Hmong home care Fresno"],
    neighborhoods: ["North Fresno", "Clovis", "Tower District", "Sunnyside", "Southeast Fresno"],
  },
  "sacramento": {
    name: "Sacramento",
    displayName: "Sacramento, CA",
    county: "Sacramento County",
    state: "California",
    stateAbbr: "CA",
    population: 524943,
    lat: 38.5816,
    lng: -121.4944,
    metaTitle: "Home Care Agencies in Sacramento, CA | RennXCare",
    metaDescription: "Find home care agencies in Sacramento, California. Compare senior care, dementia support, and 24-hour in-home care services in the Sacramento metro area.",
    h1: "Best Home Care Agencies in Sacramento, California",
    intro: "Sacramento families trust RennXCare to connect them with qualified, compassionate home care agencies. Browse verified providers across Sacramento, Elk Grove, Roseville, and surrounding communities.",
    primaryKeywords: ["home care agencies Sacramento", "in-home care Sacramento CA", "senior care Sacramento", "elder care Sacramento County"],
    longTailKeywords: ["home care near me Sacramento", "dementia care Sacramento CA", "24-hour home care Sacramento", "in-home senior care Elk Grove"],
    neighborhoods: ["Midtown", "Land Park", "East Sacramento", "Natomas", "Elk Grove"],
  },
};

/* ------------------------------------------------------------------
   SERVICES LIST — used in filter dropdowns
   ------------------------------------------------------------------ */
const RENNXCARE_SERVICES = [
  "Personal Care",
  "Dementia Care",
  "24-Hour Care",
  "Companionship",
  "Respite Care",
  "Hospice Support",
  "Meal Preparation",
  "Transportation",
  "Light Housekeeping",
  "Medication Reminders",
  "Errands",
];

/* ------------------------------------------------------------------
   HELPER FUNCTIONS
   ------------------------------------------------------------------ */

/** Return agencies for a given citySlug */
function getAgenciesByCity(citySlug) {
  return RENNXCARE_AGENCIES.filter(a => a.citySlug === citySlug);
}

/** Return featured agencies across all cities */
function getFeaturedAgencies(limit = 6) {
  return RENNXCARE_AGENCIES.filter(a => a.featured).slice(0, limit);
}

/** Return a single agency by slug */
function getAgencyBySlug(slug) {
  return RENNXCARE_AGENCIES.find(a => a.slug === slug) || null;
}

/** Return cities that have at least one agency record */
function getActiveCities() {
  const slugs = [...new Set(RENNXCARE_AGENCIES.map(a => a.citySlug))];
  return slugs.map(s => CA_CITIES[s]).filter(Boolean);
}

/** Return star HTML string for a numeric rating */
function renderStars(rating) {
  const full  = Math.floor(rating);
  const half  = (rating % 1) >= 0.5 ? 1 : 0;
  const empty = 5 - full - half;
  return "★".repeat(full) + (half ? "½" : "") + "☆".repeat(empty);
}

/** Slugify a string */
function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}
